### PR TITLE
fixes ...path/:username bug, ui & validation improvements

### LINKED ISSUE #129: !!! profile page url params issue !!!
@bonham000 This is an interesting one that I just stumbled upon... if you try to type in the url of a user's profile, let's take `Weezlo` for example, but you ignore case, which is my general instinct when typing in URLs, we have problems. Because the component is set up to fetch the user info from the db/redux based on that parameter, if the case is not exact, the info does not get pulled. The fcc data still gets scraped, but no other user info is retrieved.

What this also means, is that you can visit the profile page of anyone - even someone that does not exist - and the page will still render with the basic shell... 

same goes for `dashboard/char/:username` routes
image
 

So this is really a 2 part issue:

1. case sensitivity for `/:username` routes - should be able to get around this fairly easily
2. triggering 404s when user tries to visit invalid `/:username` routes

Any thoughts as how to get around the second one?

**EDIT:** I have the first part solved, at least for profile page. 

**EDIT 2:** Both issues solved for ChatController as well now. It looks like you may have already thought of this partly? I just implemented what I thought would fix only the first of the two issues, but it seems to fix both. Not typing in `/dashboard/chat/peter` or some other name that does not exist as a user, it just goes to main mess hall, looks to be because of the `if/else` in `mapStateToProps`

Just when we thought we were almost done...

### PR DESCRIPTION
**Pull request by no-stack-dub-sack**
- fixes bug described in issue #129 
- makes improvements to responsiveness at tablet resolutions for public profile page (looked a bit funny before, username label did not render right and user avatar would be at the top of a tall, narrow column, this stacks the containers a bit earlier using some custom event listeners)
- improves validation code for preferences page - if a user has github data that breaks validation rules, previous validation would not pick up on it (ex. length of display name and location) since user would not be explicitly typing it in. But it is still important to limit the length of these sections to ensure proper UI rendering. We could approach this another way down the line, GH seems to just hide overflow for long location entries and such, but this works for now.
- other random extremely minor fixes
closes #129

### CODE REVIEW

File: client/src/actions/scrape-fcc.js [hunk 1]
```diff
@@ -29,7 +29,7 @@ export const scrapeFccStats = (user) => (dispatch) => {
         return item.text();
       });
     }).then(items => {
-      return items.length;
+      return items.length.toString();
```
Comment (no-stack-dub-sack) [inline client/src/actions/scrape-fcc.js]: ☝️ whoops, this was not necessary, was messing around because total challenges was not rendering, but this was apparently because of a long time typo that went unnoticed (`totalChallneges`)

**Comment by bonham000** [comment]
# 100

🎉 🎂 🎁 🎈 :stadium: 🌟 :robot: 🚀 

_**mega!**_
